In [184]:
import pandas as pd
import numpy as np
import json

In [185]:
data =  open('CongressDataFinal.json')

senators = json.load(data)

senators

{'Alexander, Lamar [R-TN]': {'Bill': 'N/A'},
 'Baldwin, Tammy [D-WI]': {'Bill 1': {'Bill Number': 'S.1196',
   'Number of Cosponsors': '1',
   'Cosponsor Info': {'Cosponsor 1': 'Sen. Johnson, Ron [R-WI]*@https://www.congress.gov/member/ron-johnson/J000293'}},
  'Bill 2': {'Bill Number': 'S.1153',
   'Number of Cosponsors': '8',
   'Cosponsor Info': {'Cosponsor 1': 'Sen. Braun, Mike  [R-IN]*@https://www.congress.gov/member/mike-braun/B001310',
    'Cosponsor 2': 'Sen. Shaheen, Jeanne [D-NH]*@https://www.congress.gov/member/jeanne-shaheen/S001181',
    'Cosponsor 3': 'Sen. Fischer, Deb [R-NE]*@https://www.congress.gov/member/deb-fischer/F000463',
    'Cosponsor 4': 'Sen. Alexander, Lamar [R-TN]@https://www.congress.gov/member/lamar-alexander/A000360',
    'Cosponsor 5': 'Sen. Burr, Richard [R-NC]@https://www.congress.gov/member/richard-burr/B001135',
    'Cosponsor 6': 'Sen. Hassan, Margaret Wood [D-NH]@https://www.congress.gov/member/margaret-hassan/H001076',
    'Cosponsor 7': 'Sen. Co

In [186]:

print(senators)

{'Alexander, Lamar [R-TN]': {'Bill': 'N/A'}, 'Baldwin, Tammy [D-WI]': {'Bill 1': {'Bill Number': 'S.1196', 'Number of Cosponsors': '1', 'Cosponsor Info': {'Cosponsor 1': 'Sen. Johnson, Ron [R-WI]*@https://www.congress.gov/member/ron-johnson/J000293'}}, 'Bill 2': {'Bill Number': 'S.1153', 'Number of Cosponsors': '8', 'Cosponsor Info': {'Cosponsor 1': 'Sen. Braun, Mike  [R-IN]*@https://www.congress.gov/member/mike-braun/B001310', 'Cosponsor 2': 'Sen. Shaheen, Jeanne [D-NH]*@https://www.congress.gov/member/jeanne-shaheen/S001181', 'Cosponsor 3': 'Sen. Fischer, Deb [R-NE]*@https://www.congress.gov/member/deb-fischer/F000463', 'Cosponsor 4': 'Sen. Alexander, Lamar [R-TN]@https://www.congress.gov/member/lamar-alexander/A000360', 'Cosponsor 5': 'Sen. Burr, Richard [R-NC]@https://www.congress.gov/member/richard-burr/B001135', 'Cosponsor 6': 'Sen. Hassan, Margaret Wood [D-NH]@https://www.congress.gov/member/margaret-hassan/H001076', 'Cosponsor 7': 'Sen. Coons, Christopher A. [D-DE]@https://www.

In [187]:
#senator = senators[0]
#prueba = information[senator]

senators['Wyden, Ron [D-OR]']

#prueba

{'Bill': 'N/A'}

In [188]:
import re

matrix_info = []

for name, bills in senators.items():
    print(name)
    bills
    senator_info = []
    senator_cosponsors=[]
    for bill in bills.values():
        if bill == 'N/A':
            continue
        if int(bill['Number of Cosponsors']) > 0:
            print('      The Cosponsors for bill ' + bill['Bill Number'] + ' are:')
            for cosponsor in bill['Cosponsor Info'].values():
                cosponsor_string = cosponsor.split('@')[0][5:].strip('*')
                #cosponsor_string = cosponsor_string.split()[0].strip(',') + ' ' + cosponsor_string.split()[len(cosponsor_string.split())-1]
                #cosponsor_string = re.sub(r'-[0-9]+', '', cosponsor_string)
                print('                     '+cosponsor_string)
                
                senator_cosponsors.append(cosponsor_string)
                
                #print('                     '+cosponsor.split('@')[0][5:].strip('*'))
        else:
            print('      Bill '+ bill['Bill Number'] + ' had no cosponsors')
            
    senator_info=[name, senator_cosponsors]
    matrix_info.append(senator_info)

    
#prueba['Bill 5']['Cosponsor Info']['Cosponsor 1'].split('@')[0].strip('Sen. ').strip('*')

Alexander, Lamar [R-TN]
Baldwin, Tammy [D-WI]
      The Cosponsors for bill S.1196 are:
                     Johnson, Ron [R-WI]
      The Cosponsors for bill S.1153 are:
                     Braun, Mike  [R-IN]
                     Shaheen, Jeanne [D-NH]
                     Fischer, Deb [R-NE]
                     Alexander, Lamar [R-TN]
                     Burr, Richard [R-NC]
                     Hassan, Margaret Wood [D-NH]
                     Coons, Christopher A. [D-DE]
                     Klobuchar, Amy [D-MN]
      The Cosponsors for bill S.1069 are:
                     Murkowski, Lisa [R-AK]
                     Cantwell, Maria [D-WA]
                     Sullivan, Dan  [R-AK]
                     Klobuchar, Amy [D-MN]
Barrasso, John [R-WY]
      The Cosponsors for bill S.3051 are:
                     Carper, Thomas R. [D-DE]
                     Cramer, Kevin [R-ND]
                     Cardin, Benjamin L. [D-MD]
                     Capito, Shelley Moore [R-WV]
       

In [189]:
matrix_info

[['Alexander, Lamar [R-TN]', []],
 ['Baldwin, Tammy [D-WI]',
  ['Johnson, Ron [R-WI]',
   'Braun, Mike  [R-IN]',
   'Shaheen, Jeanne [D-NH]',
   'Fischer, Deb [R-NE]',
   'Alexander, Lamar [R-TN]',
   'Burr, Richard [R-NC]',
   'Hassan, Margaret Wood [D-NH]',
   'Coons, Christopher A. [D-DE]',
   'Klobuchar, Amy [D-MN]',
   'Murkowski, Lisa [R-AK]',
   'Cantwell, Maria [D-WA]',
   'Sullivan, Dan  [R-AK]',
   'Klobuchar, Amy [D-MN]']],
 ['Barrasso, John [R-WY]',
  ['Carper, Thomas R. [D-DE]',
   'Cramer, Kevin [R-ND]',
   'Cardin, Benjamin L. [D-MD]',
   'Capito, Shelley Moore [R-WV]',
   'Van Hollen, Chris [D-MD]',
   'Inhofe, James M. [R-OK]',
   'Boozman, John [R-AR]',
   'Duckworth, Tammy [D-IL]',
   'Heinrich, Martin [D-NM]']],
 ['Bennet, Michael [D-CO]', []],
 ['Blackburn, Marsha [R-TN]', []],
 ['Blumenthal, Richard [D-CT]',
  ['Graham, Lindsey [R-SC]', 'Whitehouse, Sheldon [D-RI]']],
 ['Blunt, Roy [R-MO]', []],
 ['Booker, Cory [D-NJ]', ['Menendez, Robert [D-NJ]']],
 ['Boozman, Jo

In [190]:
for item in matrix_info:
    #print(item[1])
    cosponsor_list = item[1]
    
    for x in range(len(cosponsor_list)):
        
        cosponsor_string = cosponsor_list[x]
        
        print(cosponsor_string)

        cosponsor_string = cosponsor_string.split()[0].strip(',') + ' [' + re.findall(r'\[(.*?)\]', cosponsor_string)[0]+ ']'

        cosponsor_string.split()[len(cosponsor_string.split())-1]
        cosponsor_string = re.sub(r'-[0-9]+', '', cosponsor_string)

        print(cosponsor_string)
        print()
        
        cosponsor_list[x] = cosponsor_string
        
        
        
    for cosponsor_string in cosponsor_list:
        print(cosponsor_string)

        #cosponsor_string = cosponsor_string.split()[0].strip(',') + ' [' + re.findall(r'\[(.*?)\]', cosponsor_string)[0]+ ']'

        #cosponsor_string.split()[len(cosponsor_string.split())-1]
        #cosponsor_string = re.sub(r'-[0-9]+', '', cosponsor_string)

        #print(cosponsor_string)
        #print()

    
    #print(item[1])
        

Johnson, Ron [R-WI]
Johnson [R-WI]

Braun, Mike  [R-IN]
Braun [R-IN]

Shaheen, Jeanne [D-NH]
Shaheen [D-NH]

Fischer, Deb [R-NE]
Fischer [R-NE]

Alexander, Lamar [R-TN]
Alexander [R-TN]

Burr, Richard [R-NC]
Burr [R-NC]

Hassan, Margaret Wood [D-NH]
Hassan [D-NH]

Coons, Christopher A. [D-DE]
Coons [D-DE]

Klobuchar, Amy [D-MN]
Klobuchar [D-MN]

Murkowski, Lisa [R-AK]
Murkowski [R-AK]

Cantwell, Maria [D-WA]
Cantwell [D-WA]

Sullivan, Dan  [R-AK]
Sullivan [R-AK]

Klobuchar, Amy [D-MN]
Klobuchar [D-MN]

Johnson [R-WI]
Braun [R-IN]
Shaheen [D-NH]
Fischer [R-NE]
Alexander [R-TN]
Burr [R-NC]
Hassan [D-NH]
Coons [D-DE]
Klobuchar [D-MN]
Murkowski [R-AK]
Cantwell [D-WA]
Sullivan [R-AK]
Klobuchar [D-MN]
Carper, Thomas R. [D-DE]
Carper [D-DE]

Cramer, Kevin [R-ND]
Cramer [R-ND]

Cardin, Benjamin L. [D-MD]
Cardin [D-MD]

Capito, Shelley Moore [R-WV]
Capito [R-WV]

Van Hollen, Chris [D-MD]
Van [D-MD]

Inhofe, James M. [R-OK]
Inhofe [R-OK]

Boozman, John [R-AR]
Boozman [R-AR]

Duckworth, Tammy [D-

Udall, Tom [D-NM]
Udall [D-NM]

Moran, Jerry [R-KS]
Moran [R-KS]

Stabenow [D-MI]
Udall [D-NM]
Moran [R-KS]
Capito, Shelley Moore [R-WV]
Capito [R-WV]

Schatz, Brian [D-HI]
Schatz [D-HI]

Blackburn, Marsha [R-TN]
Blackburn [R-TN]

Cortez Masto, Catherine  [D-NV]
Cortez [D-NV]

Fischer, Deb [R-NE]
Fischer [R-NE]

Blumenthal, Richard [D-CT]
Blumenthal [D-CT]

Hoeven, John [R-ND]
Hoeven [R-ND]

Wyden, Ron [D-OR]
Wyden [D-OR]

Capito [R-WV]
Schatz [D-HI]
Blackburn [R-TN]
Cortez [D-NV]
Fischer [R-NE]
Blumenthal [D-CT]
Hoeven [R-ND]
Wyden [D-OR]
Menendez, Robert [D-NJ]
Menendez [D-NJ]

Risch, James E. [R-ID]
Risch [R-ID]

Gardner, Cory [R-CO]
Gardner [R-CO]

Wyden, Ron [D-OR]
Wyden [D-OR]

Cornyn, John [R-TX]
Cornyn [R-TX]

Blumenthal, Richard [D-CT]
Blumenthal [D-CT]

Daines, Steve [R-MT]
Daines [R-MT]

Coons, Christopher A. [D-DE]
Coons [D-DE]

Moran, Jerry [R-KS]
Moran [R-KS]

Kaine, Tim [D-VA]
Kaine [D-VA]

Grassley, Chuck [R-IA]
Grassley [R-IA]

Van Hollen, Chris [D-MD]
Van [D-MD]

Cott

In [191]:
matrix_info

[['Alexander, Lamar [R-TN]', []],
 ['Baldwin, Tammy [D-WI]',
  ['Johnson [R-WI]',
   'Braun [R-IN]',
   'Shaheen [D-NH]',
   'Fischer [R-NE]',
   'Alexander [R-TN]',
   'Burr [R-NC]',
   'Hassan [D-NH]',
   'Coons [D-DE]',
   'Klobuchar [D-MN]',
   'Murkowski [R-AK]',
   'Cantwell [D-WA]',
   'Sullivan [R-AK]',
   'Klobuchar [D-MN]']],
 ['Barrasso, John [R-WY]',
  ['Carper [D-DE]',
   'Cramer [R-ND]',
   'Cardin [D-MD]',
   'Capito [R-WV]',
   'Van [D-MD]',
   'Inhofe [R-OK]',
   'Boozman [R-AR]',
   'Duckworth [D-IL]',
   'Heinrich [D-NM]']],
 ['Bennet, Michael [D-CO]', []],
 ['Blackburn, Marsha [R-TN]', []],
 ['Blumenthal, Richard [D-CT]', ['Graham [R-SC]', 'Whitehouse [D-RI]']],
 ['Blunt, Roy [R-MO]', []],
 ['Booker, Cory [D-NJ]', ['Menendez [D-NJ]']],
 ['Boozman, John [R-AR]',
  ['Perdue [R-GA]', 'Leahy [D-VT]', 'Perdue [R-GA]', 'Leahy [D-VT]']],
 ['Braun, Mike [R-IN]', ['Young [R-IN]']],
 ['Brown, Sherrod [D-OH]', ['Klobuchar [D-MN]', 'Blunt [R-MO]']],
 ['Burr, Richard [R-NC]',
  

In [192]:
#ADJACENCY MATRIX

In [193]:
senator_names = []


for item in matrix_info:
    cosponsor_string = item[0]
    cosponsor_string = cosponsor_string.split()[0].strip(',') + ' [' + re.findall(r'\[(.*?)\]', cosponsor_string)[0]+ ']'
    
    cosponsor_string.split()[len(cosponsor_string.split())-1]
    cosponsor_string = re.sub(r'-[0-9]+', '', cosponsor_string)
    senator_names.append(cosponsor_string)
    
    
#for item in matrix_info:
#    row = []
#    senator_names.append(item[0])
    
senator_names

['Alexander [R-TN]',
 'Baldwin [D-WI]',
 'Barrasso [R-WY]',
 'Bennet [D-CO]',
 'Blackburn [R-TN]',
 'Blumenthal [D-CT]',
 'Blunt [R-MO]',
 'Booker [D-NJ]',
 'Boozman [R-AR]',
 'Braun [R-IN]',
 'Brown [D-OH]',
 'Burr [R-NC]',
 'Cantwell [D-WA]',
 'Capito [R-WV]',
 'Cardin [D-MD]',
 'Carper [D-DE]',
 'Casey [D-PA]',
 'Cassidy [R-LA]',
 'Collins [R-ME]',
 'Coons [D-DE]',
 'Cornyn [R-TX]',
 'Cortez [D-NV]',
 'Cotton [R-AR]',
 'Cramer [R-ND]',
 'Crapo [R-ID]',
 'Cruz [R-TX]',
 'Daines [R-MT]',
 'Duckworth [D-IL]',
 'Durbin [D-IL]',
 'Enzi [R-WY]',
 'Ernst [R-IA]',
 'Feinstein [D-CA]',
 'Fischer [R-NE]',
 'Gardner [R-CO]',
 'Gillibrand [D-NY]',
 'Graham [R-SC]',
 'Grassley [R-IA]',
 'Harris [D-CA]',
 'Hassan [D-NH]',
 'Hawley [R-MO]',
 'Heinrich [D-NM]',
 'Hirono [D-HI]',
 'Hoeven [R-ND]',
 'Hyde-Smith [R-MS]',
 'Inhofe [R-OK]',
 'Isakson [R-GA]',
 'Johnson [R-WI]',
 'Jones [D-AL]',
 'Kaine [D-VA]',
 'Kelly [D-AZ]',
 'Kennedy [R-LA]',
 'King [I-ME]',
 'Klobuchar [D-MN]',
 'Lankford [R-OK]',


In [248]:
#row = np.zeros(len(senator_names), dtype=int)
#cosponsors = matrix_info[1][1]

numerical_matrix = []

#print(matrix_info[1][1])

for matrix_row in matrix_info:
    
    row = np.zeros(len(senator_names), dtype=int)
    cosponsors = matrix_row[1]
    
    for x in range(len(row)):
        for cosponsor in cosponsors:
            #print(cosponsor)
            if cosponsor == senator_names[x]:
                row[x] += 1
    numerical_matrix.append(row)

#print(row)

#print(len(cosponsors))
#print(senator_names[0])
#print(np.sum(row))

adjacency_transpose = np.array(numerical_matrix)
#adjacency = adjacency + adjacency.transpose()
adjacency = adjacency_transpose.transpose()
#print(numerical_matrix)
print(adjacency)

[[0 1 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]


In [249]:
np.sum(adjacency[1])

13

In [250]:
np.savetxt('adjacency.csv', adjacency, delimiter=',')

In [251]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

ADJACENCY = pd.DataFrame(adjacency, senator_names, senator_names)
ADJACENCY

Alexander [R-TN]  Baldwin [D-WI]  Barrasso [R-WY]  \
Alexander [R-TN]                  0               1                0   
Baldwin [D-WI]                    0               0                0   
Barrasso [R-WY]                   0               0                0   
Bennet [D-CO]                     0               0                0   
Blackburn [R-TN]                  0               0                0   
Blumenthal [D-CT]                 0               0                0   
Blunt [R-MO]                      0               0                0   
Booker [D-NJ]                     0               0                0   
Boozman [R-AR]                    0               0                1   
Braun [R-IN]                      0               1                0   
Brown [D-OH]                      0               0                0   
Burr [R-NC]                       0               1                0   
Cantwell [D-WA]                   0               1                0   
Capito [R-WV]                     0               0                1   
Cardin [D-MD]                     0               0                1   
Carper [D-DE]                     0               0                1   
Casey [D-PA]                      0               0                0   
Cassidy [R-LA]                    0               0                0   
Collins [R-ME]                    0               0                0   
Coons [D-DE]                      0               1                0   
Cornyn [R-TX]                     0               0                0   
Cortez [D-NV]                     0               0                0   
Cotton [R-AR]                     0               0                0   
Cramer [R-ND]                     0               0                1   
Crapo [R-ID]                      0               0                0   
Cruz [R-TX]                       0               0                0   
Daines [R-MT]                     0               0                0   
Duckworth [D-IL]                  0               0                1   
Durbin [D-IL]                     0               0                0   
Enzi [R-WY]                       0               0                0   
Ernst [R-IA]                      0               0                0   
Feinstein [D-CA]                  0               0                0   
Fischer [R-NE]                    0               1                0   
Gardner [R-CO]                    0               0                0   
Gillibrand [D-NY]                 0               0                0   
Graham [R-SC]                     0               0                0   
Grassley [R-IA]                   0               0                0   
Harris [D-CA]                     0               0                0   
Hassan [D-NH]                     0               1                0   
Hawley [R-MO]                     0               0                0   
Heinrich [D-NM]                   0               0                1   
Hirono [D-HI]                     0               0                0   
Hoeven [R-ND]                     0               0                0   
Hyde-Smith [R-MS]                 0               0                0   
Inhofe [R-OK]                     0               0                1   
Isakson [R-GA]                    0               0                0   
Johnson [R-WI]                    0               1                0   
Jones [D-AL]                      0               0                0   
Kaine [D-VA]                      0               0                0   
Kelly [D-AZ]                      0               0                0   
Kennedy [R-LA]                    0               0                0   
King [I-ME]                       0               0                0   
Klobuchar [D-MN]                  0               2                0   
Lankford [R-OK]                   0               0                0   
Leahy [D-VT]                      0               0        

In [252]:
ADJACENCY.to_csv('adjacency_nice.csv')

In [253]:
from sklearn.preprocessing import normalize

In [257]:
#We'll be working with the transpose of T'. Thus, normalizing the colums of T' is the equivalent of noramlizin the rows of A
nadjacency = normalize(adjacency, axis=1, norm='l1')
nadjacency

#check if there are senators who have not cosponsored anything

for x in range(len(nadjacency)):
    row = nadjacency[x]
    sum = np.sum(row)
    #print(np.sum(row))
    
    #if there is a senator who has not cosponsored, the sum will be 0
    if sum == 0:
        print("   valiste cola")
        for y in range(len(row)):
            nadjacency[x][y] = 1/len(row)
            
        print(nadjacency[x])
        


   valiste cola
[0.00980392 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392
 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392
 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392
 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392
 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392
 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392
 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392
 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392
 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392
 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392
 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392
 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392
 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392
 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392 0.00980392
 0.00980392 0.00980392 0.00980392 0.00980392 0

In [258]:
pd.DataFrame(nadjacency, senator_names, senator_names)

Alexander [R-TN]  Baldwin [D-WI]  Barrasso [R-WY]  \
Alexander [R-TN]           0.000000        0.142857         0.000000   
Baldwin [D-WI]             0.000000        0.000000         0.000000   
Barrasso [R-WY]            0.000000        0.000000         0.000000   
Bennet [D-CO]              0.000000        0.000000         0.000000   
Blackburn [R-TN]           0.000000        0.000000         0.000000   
Blumenthal [D-CT]          0.000000        0.000000         0.000000   
Blunt [R-MO]               0.000000        0.000000         0.000000   
Booker [D-NJ]              0.000000        0.000000         0.000000   
Boozman [R-AR]             0.000000        0.000000         0.062500   
Braun [R-IN]               0.000000        0.071429         0.000000   
Brown [D-OH]               0.000000        0.000000         0.000000   
Burr [R-NC]                0.000000        0.125000         0.000000   
Cantwell [D-WA]            0.000000        0.083333         0.000000   
Capito [R-WV]              0.000000        0.000000         0.047619   
Cardin [D-MD]              0.000000        0.000000         0.071429   
Carper [D-DE]              0.000000        0.000000         0.090909   
Casey [D-PA]               0.000000        0.000000         0.000000   
Cassidy [R-LA]             0.000000        0.000000         0.000000   
Collins [R-ME]             0.000000        0.000000         0.000000   
Coons [D-DE]               0.000000        0.040000         0.000000   
Cornyn [R-TX]              0.000000        0.000000         0.000000   
Cortez [D-NV]              0.000000        0.000000         0.000000   
Cotton [R-AR]              0.000000        0.000000         0.000000   
Cramer [R-ND]              0.000000        0.000000         0.050000   
Crapo [R-ID]               0.000000        0.000000         0.000000   
Cruz [R-TX]                0.000000        0.000000         0.000000   
Daines [R-MT]              0.000000        0.000000         0.000000   
Duckworth [D-IL]           0.000000        0.000000         0.100000   
Durbin [D-IL]              0.000000        0.000000         0.000000   
Enzi [R-WY]                0.000000        0.000000         0.000000   
Ernst [R-IA]               0.000000        0.000000         0.000000   
Feinstein [D-CA]           0.000000        0.000000         0.000000   
Fischer [R-NE]             0.000000        0.083333         0.000000   
Gardner [R-CO]             0.000000        0.000000         0.000000   
Gillibrand [D-NY]          0.000000        0.000000         0.000000   
Graham [R-SC]              0.000000        0.000000         0.000000   
Grassley [R-IA]            0.000000        0.000000         0.000000   
Harris [D-CA]              0.000000        0.000000         0.000000   
Hassan [D-NH]              0.000000        0.047619         0.000000   
Hawley [R-MO]              0.000000        0.000000         0.000000   
Heinrich [D-NM]            0.000000        0.000000         0.100000   
Hirono [D-HI]              0.000000        0.000000         0.000000   
Hoeven [R-ND]              0.000000        0.000000         0.000000   
Hyde-Smith [R-MS]          0.000000        0.000000         0.000000   
Inhofe [R-OK]              0.000000        0.000000         0.066667   
Isakson [R-GA]             0.000000        0.000000         0.000000   
Johnson [R-WI]             0.000000        0.111111         0.000000   
Jones [D-AL]               0.000000        0.000000         0.000000   
Kaine [D-VA]               0.000000        0.000000         0.000000   
Kelly [D-AZ]               0.009804        0.009804         0.009804   
Kennedy [R-LA]             0.000000        0.000000         0.000000   
King [I-ME]                0.000000        0.000000         0.000000   
Klobuchar [D-MN]           0.000000        0.068966         0.000000   
Lankford [R-OK]            0.000000        0.000000         0.000000   
Leahy [D-VT]               0.000000        0.000000        

In [276]:
t = nadjacency.transpose()
t

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.14285714, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.07692308, 0.1       , ..., 0.        , 0.        ,
        0.08333333],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [409]:
def page_rank(t, p, iterations):
    
    dim = len(t)
    s = np.full((dim,dim), 1/dim)
    
    m = (1-p)*t + p*s
    
    v = np.random.rand(len(m), 1)
    v = v / np.linalg.norm(v, 1)
    
    for x in range(iterations):
        v = m @ v
        
    return v
        

In [439]:
importance_vector = page_rank(t, 0.15, 1000)
importance_vector

array([[0.00148295],
       [0.00949366],
       [0.00461297],
       [0.00148295],
       [0.00148295],
       [0.00651783],
       [0.00148295],
       [0.00156173],
       [0.0019151 ],
       [0.00158799],
       [0.00168397],
       [0.00953882],
       [0.00157298],
       [0.00970018],
       [0.02763726],
       [0.0037715 ],
       [0.01137483],
       [0.00291067],
       [0.02650596],
       [0.00148295],
       [0.06663247],
       [0.0121414 ],
       [0.00148295],
       [0.00148295],
       [0.00148295],
       [0.00148295],
       [0.00433839],
       [0.00384465],
       [0.00148295],
       [0.00216648],
       [0.00148295],
       [0.00148295],
       [0.002961  ],
       [0.03640524],
       [0.00148295],
       [0.01503691],
       [0.01849396],
       [0.00148295],
       [0.00148295],
       [0.01454773],
       [0.00148295],
       [0.00148295],
       [0.0039137 ],
       [0.00148295],
       [0.00148295],
       [0.05349121],
       [0.00625028],
       [0.001

In [460]:
print(np.amax(importance_vector))
index = np.argmax(importance_vector)
print(index)
print(importance_vector[index])
importance_vector = importance_vector/np.amax(importance_vector)
print(importance_vector)

0.09354739579297372
77
[0.0935474]
[[0.01585235]
 [0.10148506]
 [0.04931158]
 [0.01585235]
 [0.01585235]
 [0.06967408]
 [0.01585235]
 [0.01669451]
 [0.02047201]
 [0.01697523]
 [0.0180013 ]
 [0.10196775]
 [0.01681481]
 [0.10369273]
 [0.29543588]
 [0.04031647]
 [0.1215943 ]
 [0.03111434]
 [0.28334258]
 [0.01585235]
 [0.7122857 ]
 [0.12978872]
 [0.01585235]
 [0.01585235]
 [0.01585235]
 [0.01585235]
 [0.04637634]
 [0.04109842]
 [0.01585235]
 [0.0231592 ]
 [0.01585235]
 [0.01585235]
 [0.03165242]
 [0.38916355]
 [0.01585235]
 [0.16074108]
 [0.19769617]
 [0.01585235]
 [0.01585235]
 [0.15551188]
 [0.01585235]
 [0.01585235]
 [0.04183657]
 [0.01585235]
 [0.01585235]
 [0.5718087 ]
 [0.06681405]
 [0.01585235]
 [0.01707731]
 [0.01585235]
 [0.10572806]
 [0.01585235]
 [0.01585235]
 [0.01585235]
 [0.01585235]
 [0.02146672]
 [0.01585235]
 [0.02004944]
 [0.01585235]
 [0.01585235]
 [0.01585235]
 [0.01585235]
 [0.1454334 ]
 [0.33975284]
 [0.19101003]
 [0.01585235]
 [0.01585235]
 [0.01585235]
 [0.01797643]

In [461]:
print(importance_vector)
imp_reshaped = importance_vector.transpose()
print(imp_reshaped[0])
r = np.argsort(imp_reshaped)
print(r[0])

[[0.01585235]
 [0.10148506]
 [0.04931158]
 [0.01585235]
 [0.01585235]
 [0.06967408]
 [0.01585235]
 [0.01669451]
 [0.02047201]
 [0.01697523]
 [0.0180013 ]
 [0.10196775]
 [0.01681481]
 [0.10369273]
 [0.29543588]
 [0.04031647]
 [0.1215943 ]
 [0.03111434]
 [0.28334258]
 [0.01585235]
 [0.7122857 ]
 [0.12978872]
 [0.01585235]
 [0.01585235]
 [0.01585235]
 [0.01585235]
 [0.04637634]
 [0.04109842]
 [0.01585235]
 [0.0231592 ]
 [0.01585235]
 [0.01585235]
 [0.03165242]
 [0.38916355]
 [0.01585235]
 [0.16074108]
 [0.19769617]
 [0.01585235]
 [0.01585235]
 [0.15551188]
 [0.01585235]
 [0.01585235]
 [0.04183657]
 [0.01585235]
 [0.01585235]
 [0.5718087 ]
 [0.06681405]
 [0.01585235]
 [0.01707731]
 [0.01585235]
 [0.10572806]
 [0.01585235]
 [0.01585235]
 [0.01585235]
 [0.01585235]
 [0.02146672]
 [0.01585235]
 [0.02004944]
 [0.01585235]
 [0.01585235]
 [0.01585235]
 [0.01585235]
 [0.1454334 ]
 [0.33975284]
 [0.19101003]
 [0.01585235]
 [0.01585235]
 [0.01585235]
 [0.01797643]
 [0.30217529]
 [0.01687242]
 [0.01

In [462]:
scores_names = []
for j in range(102):
    scores_names.append([imp_reshaped[0][j], senator_names[j]])
    
print(scores_names)

[[0.015852350640590474, 'Alexander [R-TN]'], [0.10148506055456645, 'Baldwin [D-WI]'], [0.04931157931667714, 'Barrasso [R-WY]'], [0.015852350640590474, 'Bennet [D-CO]'], [0.015852350640590474, 'Blackburn [R-TN]'], [0.06967408098874701, 'Blumenthal [D-CT]'], [0.015852350640590474, 'Blunt [R-MO]'], [0.016694506768371843, 'Booker [D-NJ]'], [0.020472010698032186, 'Boozman [R-AR]'], [0.0169752254776323, 'Braun [R-IN]'], [0.018001300759756728, 'Brown [D-OH]'], [0.10196775098838073, 'Burr [R-NC]'], [0.016814814786626324, 'Cantwell [D-WA]'], [0.10369272733254223, 'Capito [R-WV]'], [0.29543588272577304, 'Cardin [D-MD]'], [0.04031647202833537, 'Carper [D-DE]'], [0.12159430129792596, 'Casey [D-PA]'], [0.03111434293019331, 'Cassidy [R-LA]'], [0.283342575426285, 'Collins [R-ME]'], [0.015852350640590474, 'Coons [D-DE]'], [0.7122856966334222, 'Cornyn [R-TX]'], [0.12978872156254423, 'Cortez [D-NV]'], [0.015852350640590474, 'Cotton [R-AR]'], [0.015852350640590474, 'Cramer [R-ND]'], [0.015852350640590474

In [463]:
scores_names_sorted = []

for j in r[0]:
    scores_names_sorted.append(scores_names[j])
    
    
print(scores_names_sorted)

[[0.015852350640590474, 'Alexander [R-TN]'], [0.015852350640590474, 'McConnell [R-KY]'], [0.015852350640590474, 'Markey [D-MA]'], [0.015852350640590474, 'Loeffler [R-GA]'], [0.015852350640590474, 'Leahy [D-VT]'], [0.015852350640590474, 'Lankford [R-OK]'], [0.015852350640590474, 'Klobuchar [D-MN]'], [0.015852350640590474, 'McSally [R-AZ]'], [0.015852350640590474, 'King [I-ME]'], [0.015852350640590474, 'Kelly [D-AZ]'], [0.015852350640590474, 'Jones [D-AL]'], [0.015852350640590474, 'Inhofe [R-OK]'], [0.015852350640590474, 'Hyde-Smith [R-MS]'], [0.015852350640590474, 'Hirono [D-HI]'], [0.015852350640590474, 'Heinrich [D-NM]'], [0.015852350640590474, 'Wyden [D-OR]'], [0.015852350640590474, 'Menendez [D-NJ]'], [0.015852350640590474, 'Murphy [D-CT]'], [0.015852350640590474, 'Murray [D-WA]'], [0.015852350640590474, 'Warner [D-VA]'], [0.015852350640590474, 'Van [D-MD]'], [0.015852350640590474, 'Tillis [R-NC]'], [0.015852350640590474, 'Stabenow [D-MI]'], [0.015852350640590474, 'Shelby [R-AL]'], 

In [464]:
import csv

In [465]:
with open('senator_scores.csv', 'w') as f:
    write = csv.writer(f)
    write.writerows(scores_names)

In [412]:
for x in range (99):
    print("For p = "+str(x/100) + ": ")
    importance_vector = page_rank(t, x/100, 1000)
    print(np.amax(importance_vector))
    index = np.argmax(importance_vector)
    print(index)
    print(importance_vector[index])


For p = 0.0: 
0.10684311230356572
77
[0.10684311]
For p = 0.01: 
0.10596342469547525
77
[0.10596342]
For p = 0.02: 
0.10508293016893627
77
[0.10508293]
For p = 0.03: 
0.10420159364198196
77
[0.10420159]
For p = 0.04: 
0.10331938025157994
77
[0.10331938]
For p = 0.05: 
0.102436255349345
77
[0.10243626]
For p = 0.06: 
0.1015521844973893
77
[0.10155218]
For p = 0.07: 
0.10066713346407188
77
[0.10066713]
For p = 0.08: 
0.09978106822005452
77
[0.09978107]
For p = 0.09: 
0.09889395493419698
77
[0.09889395]
For p = 0.1: 
0.09800575996966718
77
[0.09800576]
For p = 0.11: 
0.09711644988002685
77
[0.09711645]
For p = 0.12: 
0.0962259914054154
77
[0.09622599]
For p = 0.13: 
0.09533435146877602
77
[0.09533435]
For p = 0.14: 
0.09444149717214088
77
[0.0944415]
For p = 0.15: 
0.09354739579297372
77
[0.0935474]
For p = 0.16: 
0.09265201478055926
77
[0.09265201]
For p = 0.17: 
0.09175532175244658
77
[0.09175532]
For p = 0.18: 
0.09085728449094577
77
[0.09085728]
For p = 0.19: 
0.08995787093966501
77
[

In [447]:
senator_names[77]


'Rubio [R-FL]'

In [438]:
#print(t)
#print(senator_names)
index = senator_names.index('Graham [R-SC]')
print(index)
print(102-r.tolist()[0].index(35))

35
26


In [375]:
from numpy import linalg as LA
from scipy.linalg import null_space

In [336]:
lambdas, evecs = LA.eigh(m)

guess = lambdas[0]
g_index = 0
for x in range(len(lambdas)):
    evalue = lambdas[x]
    if abs(evalue-1) < abs(guess-1):
        guess = evalue
        g_index = x


print(guess)
print(g_index)

1.0033376427396157
100


In [342]:
#lambdas[100]
#np.sum(evecs[100])
importance_vector = evecs[100]
for number in importance_vector:
    print(number)

-0.0048831926644491205
-0.0003542384228970504
-0.0022331939224174095
0.0004618876648989697
0.00020332148854028474
-0.0004962423746322667
-6.725581693597276e-05
-0.00034104591802917655
0.0004071335769258253
7.83563129133799e-05
0.0003528316859697434
-0.0004660317243789741
0.0030590223170180605
0.000622159780857887
3.226845954822132e-05
0.0005743631521218852
0.0008638087313858366
0.0014922567986071396
0.004672346389584404
0.0022951411104182883
-0.0020382385515751306
-0.0011410410307160213
0.0003006679690859301
0.00010486583004605358
-0.0032765381365180294
-0.003266490226956826
0.0011882560279082015
-0.00021343080750421337
-0.008582541907249433
-0.010520988099455423
0.013600816583896334
0.02566474204140889
-0.0222515894045053
0.12027753742180279
0.09416091008798745
-0.0709129623406019
-0.13559988491214006
-0.008810155056036575
-0.025344889280833848
0.03929011571476036
0.017637041405121602
-0.09575571317221537
0.004548111197357331
-0.031562177744724924
-0.05492191030523291
-0.0371339185991

In [49]:
#Codigo inservible para asegurarme de que no hubiera senadors con el mismo apellido del mismo estado y partido. Como en efecto no los hay, puedo construir la matrz muchisimo mas rapido

names = list(senators.keys())

In [67]:

names = list(senators.keys())

for x in range(len(names)):
    names[x] = names[x].split()[1] + ' ' +names[x].split()[2]
    
for x in range(len(names)):
    print(names[x])
    print(names.count(names[x]))
    
print(len(names))
    

#names[0].split()[1] + ' ' +names[0].split()[2]

Lamar [R-TN]
1
Tammy [D-WI]
1
John [R-WY]
1
Michael [D-CO]
1
Marsha [R-TN]
1
Richard [D-CT]
1
Roy [R-MO]
1
Cory [D-NJ]
1
John [R-AR]
1
Mike [R-IN]
1
Sherrod [D-OH]
1
Richard [R-NC]
1
Maria [D-WA]
1
Shelley [R-WV]
1
Ben [D-MD]
1
Thomas [D-DE]
1
Bob [D-PA]
1
Bill [R-LA]
1
Susan [R-ME]
1
Christopher [D-DE]
1
John [R-TX]
1
Masto, Catherine
1
Tom [R-AR]
1
Kevin [R-ND]
1
Mike [R-ID]
1
Ted [R-TX]
1
Steve [R-MT]
1
Tammy [D-IL]
1
Richard [D-IL]
1
Michael B.
1
Joni [R-IA]
1
Dianne [D-CA]
1
Deb [R-NE]
1
Cory [R-CO]
1
Kirsten [D-NY]
1
Lindsey [R-SC]
1
Charles [R-IA]
1
Kamala D.
1
Maggie [D-NH]
1
Josh [R-MO]
1
Martin [D-NM]
1
Mazie [D-HI]
1
John [R-ND]
1
Cindy [R-MS]
1
Jim [R-OK]
1
Johnny [R-GA]
1
Ron [R-WI]
1
Doug [D-AL]
1
Timothy [D-VA]
1
Mark [D-AZ]
1
John [R-LA]
1
Angus [I-ME]
1
Amy [D-MN]
1
James [R-OK]
1
Patrick [D-VT]
1
Mike [R-UT]
1
Kelly [R-GA]
1
Joseph [D-WV]
1
Edward [D-MA]
1
Mitch [R-KY]
1
Martha [R-AZ]
1
Robert [D-NJ]
1
Jeff [D-OR]
1
Jerry [R-KS]
1
Lisa [R-AK]
1
Christopher [D-CT]
1
Pa

In [ ]:
for(int i = 0; i < 10; 1++)
{
    Console.WriteLine("Roy me la pela");
}